version: "3"
services:
  mongo:
    image: mongo:3.4.23
    ports:
      - "27017:27017"
    volumes:
      - mongo_service_volume:/data/db
  postgres:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blueprint_roa_golang
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  simple_jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  # traefik:
  #   image: traefik:2.5.1
  #   ports:
  #   - 80:80
  #   volumes:
  #   - $PWD/traefik.yaml:/etc/traefik/traefik.yaml
  #   - $PWD/traefik-dyn.yaml:/etc/traefik/traefik-dyn.yaml
  # echo:
  #   image: ealen/echo-server:latest
  #   ports:
  #   - 8888:8888
  #   environment:
  #   - PORT=8888
  # auth:
  #   image: auth:latest
  #   ports:
  #   - 3002:3002
  #   - 3003:3003
  #   environment:
  #   - PORT=3002
  #   - HTTP_PORT=3003
  #   - JAEGER_HOST=simple_jaeger
  #   - DB_HOST=postgres
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   links:
  #     - postgres

volumes:
  mongo_service_volume:
    driver: local
  postgres-data: