http:
  middlewares:
    auth:
      forwardAuth:
        address: http://auth:3003/api/v1/auth/verification
  services:
    echo:
      loadBalancer:
        servers:
          - url: http://echo:8888
  routers:
    echoRouterWithAuth:
      entryPoints:
        - web
      rule: "PathPrefix(`/echo-service/guard`)"
      service: echo
      middlewares:
        - auth
    echoRouterNoAuth:
      entryPoints:
        - web
      rule: "PathPrefix(`/echo-service`)"
      service: echo
