package constants

type ErrorCode int

const (
	INTERNAL ErrorCode = iota + 1
	BAD_REQUEST
	AUTHORIZATION_REQUIRED
	AUTHORIZATION_INVALID
	OTP_TOKEN_REQUIRED
	OTP_TOKEN_INVALID
	LOGIN_PASSCODE_FAIL
)
